FROM luntlab/bw-pytorch:v1.8.0
MAINTAINER <bjlunt2@illinois.edu>

RUN apt update && \
	apt install -y git cmake && \
	rm -rf /var/lib/apt/lists/*
RUN conda install -y ninja pillow libpng jpeg
RUN cd /tmp/ && \
	git clone https://github.com/pytorch/vision.git && \
	cd vision && \
	git checkout v0.9.0 && \
	TORCH_CUDA_ARCH_LIST="3.5" FORCE_CUDA=1 PYTORCH_VERSION="1.8.0a0+37c1f4a" python setup.py install && \
	cd .. && \
	rm -rf vision
RUN cd /tmp/ && \
	git clone https://github.com/pytorch/text.git && \
	cd text && \
	git checkout v0.9.0-rc5 && \
	git submodule update --init --recursive && \
	TORCH_CUDA_ARCH_LIST="3.5" FORCE_CUDA=1 PYTORCH_VERSION="1.8.0a0+37c1f4a" python setup.py install && \
	cd .. && \
	rm -rf text
