FROM nvidia/cuda:11.2.1-cudnn8-devel-centos7
MAINTAINER "Bryan J. Lunt <bjlunt2@illinois.edu>"

#Cudnn is in /usr
#NCCL is in /usr
#CUDA toolkit in /usr/local/CUDA



#Need Cmake
#Need Git
#need which
#Need python3 / miniconda3

#Need newer gcc/g++
